[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ice_cream_shop = { path = "../ice_cream_shop" }
serde_json = "1.0.117"
