[package]
name = "screen"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
ice_cream_shop = { path = "../ice_cream_shop" }
robot = { path = "../robot" }
tokio = "1.38.0"
futures = "0.3.30"
