[package]
name = "tp1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.114"
rayon = "1.9.0"
serde = { version = "1.0.197", features = ["derive"] }
