[package]
name = "robot"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.3"
actix-rt = "2.9.0"
ice_cream_shop = { path = "../ice_cream_shop" }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tokio = "1.38.0"
